config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '', to: 'pages#home', as: :home
  get 'hr_home', to: 'pages#hr_home', as: :hr_home
  root to: 'passthrough#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :packages, only: [:index, :show] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy]

  scope :hr_home do
    resources :company_policies, only: [:edit, :update]
    get 'all_bookings', to: 'pages#all_bookings', as: :all_bookings
  end
end

app/views/shared/_booking_car_card.html.erb
<div class="billboard-card">
  <div class="card card-2">
    <div class="card-content">
      <div class="misc">
        <%= image_tag @booking.package.car.picture %>
        <span>
          <abbr><%= @booking.package.car.name %></abbr>
            <small>
              <i><%= @booking.package.car.car_category %></i>
              <p><%= @booking.package.start_date.strftime('%b %d, %Y') %> – <%= @booking.package.end_date.strftime('%b %d, %Y') %></p>
            </small>
          </span>
        </div>
      </div>
      <div class="card-provider">
        <%= image_tag @booking.package.car.photo %>
        <small>
          <%= @booking.package.car.address.split(",")[0] %>
          <br>
          <%= @booking.package.car.address.split(",")[1] %>
        </small>
      </div>
      <div class="card-price">
       <p><%=@booking.package.car.price %> € / Day</p>
      </div>
    </div>
</div>

app/views/shared/_booking_hotel_card.html.erb
<div class="billboard-card">
  <div class="card card-2">
    <div class="card-content">
      <div class="misc">
        <%= image_tag @booking.package.hotel.photo %>
        <span>
          <abbr><%= @booking.package.hotel.name %></abbr>
          <small>
            <i><% @booking.package.hotel.stars.times do %>
              ⭐️
              <% end %></i>
              <p><%= @booking.package.start_date.strftime('%b %d, %Y') %> – <%= @booking.package.end_date.strftime('%b %d, %Y') %></p>
            </small>
          </span>
        </div>
      </div>
      <div class="card-provider">
        <%= image_tag @booking.package.hotel.logo %>
        <small>
          <%= @booking.package.hotel.address.split(",")[0] %>
          <br>
          <%= @booking.package.hotel.address.split(",")[1] %>
        </small>
      </div>
      <div class="card-price">
         <p><%=@booking.package.hotel.price %> € / Night</p>
      </div>
    </div>
</div>

app/views/shared/_booking_train_card.html.erb
<div class="billboard-card">
  <div class="card card-2">
    <div class="card-content">
      <div class="schedules">
        <ul>
          <li class="tab active">Inward</li>
          <li class="tab">Outward</li>
        </ul>
        <div class="schedule">
          <span>
            <abbr><%= @booking.package.train_from.dep_city %> – <%=@booking.package.train_from.arr_city%></abbr>
            <small>
              <i><%= @booking.package.train_from.category %></i>
              <p><%= @booking.package.start_date.strftime('%b %d, %Y') %>, <%= @booking.package.train_from.dep_time %> – <%= @booking.package.train_from.arr_time %></p>
            </small>
          </span>
        </div>
        <div class="schedule hidden">
          <span>
            <abbr><%= @booking.package.train_to.dep_city %> – <%=@booking.package.train_to.arr_city%></abbr>
            <small>
              <i><%= @booking.package.train_from.category %></i>
              <p><%= @booking.package.start_date.strftime('%b %d, %Y') %>, <%= @booking.package.train_to.dep_time %> – <%= @booking.package.train_to.arr_time %></p>
            </small>
          </span>
        </div>
      </div>
    </div>
    <div class="card-provider">
      <%= image_tag @booking.package.train_from.photo %>
      <small>
        Deutsche Bahn
        <br>
        <%= @booking.package.train_from.train_number %>
      </small>
    </div>
    <div class="card-price">
      <p><%= @booking.package.train_price %> € / Trip</p>
    </div>
  </div>
</div>

app/views/shared/_car_card.html.erb
<div class="billboard-card">
  <div class="card card-2">
    <div class="card-content">
      <div class="misc">
         <%= image_tag @package.car.picture %>
        <span>
          <abbr><%= @package.car.name %></abbr>
            <small>
              <i><%= @package.car.car_category %></i>
              <p><%= @package.start_date.strftime('%b %d, %Y') %> – <%= @package.end_date.strftime('%b %d, %Y') %></p>
            </small>
          </span>
        </div>
      </div>
      <div class="card-provider">
        <%= image_tag @package.car.photo %>
        <small>
          <%= @package.car.address.split(",")[0] %>
          <br>
          <%= @package.car.address.split(",")[1] %>
        </small>
      </div>
      <div class="card-price">
        <p><%=@package.car.price %> € / Day</p>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    TravelBuddy established in 2019
  </div>
</div>

app/views/shared/_hotel_card.html.erb
<div class="billboard-card">
  <div class="card card-2">
    <div class="card-content">
      <div class="misc">
        <%= image_tag @package.hotel.photo %>
        <span>
          <abbr><%= @package.hotel.name %></abbr>
          <small>
            <i><% @package.hotel.stars.times do %>
              ⭐️
              <% end %></i>
              <p><%= @package.start_date.strftime('%b %d, %Y') %> – <%= @package.end_date.strftime('%b %d, %Y') %></p>
            </small>
          </span>
        </div>
      </div>
      <div class="card-provider">
        <%= image_tag @package.hotel.logo %>
        <small>
          <%= @package.hotel.address.split(",")[0] %>
          <br>
          <%= @package.hotel.address.split(",")[1] %>
        </small>
      </div>
      <div class="card-price">
        <p><%=@package.hotel.price %> € / Night</p>
      </div>
    </div>
</div>

app/views/shared/_hr_header.html.erb
<div class="row hr-header">
  <div class="column">
    <h1><%= current_user.company.name %></h1>
    <p class="no-margin-bottom">From <strong><%= Date.new(2019,12,01).strftime('%b %d') %></strong> to <strong><%= Date.new(2019,12,31).strftime('%b %d, %Y') %></strong></p>
  </div>
  <div class="column content-down total-price">
    <div id="total-price">€ <%= number_with_delimiter(Company.first.spend_total, :delimiter => ' ') %><i class="fas fa-sort-up"></i></div>
    <small class="no-margin-bottom">Total costs in selected month</small>
  </div>
</div>

app/views/shared/_hr_navigation.html.erb
<div class="row hr-nav">
  <div class="column content-down">
    <%= link_to 'Dashboard', hr_home_path, class: "#{action_name == 'hr_home' ? 'active' : ''}" %>
    <%= link_to 'Company policy', edit_company_policy_path(current_user.company.company_policy), class: "#{request.path_info.include?('company_policies') ? 'active' : ''}" %>
    <%= link_to 'Corporate payment', "#" %>
    <%= link_to 'All bookings', all_bookings_path, class: "#{action_name == 'all_bookings' ? 'active' : ''}" %>
  </div>
</div>

app/views/shared/_map.html.erb
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'navbar-lewagon-white' if request.path_info.include?('hr_home') %>">
  <div class="container">

    <%= link_to home_path, class: "navbar-brand avatar" do %>
      <%= image_tag "https://res.cloudinary.com/dpk0jilwo/image/upload/v1575546669/logo_qq7llj.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav mr-auto">

        <% if user_signed_in? %>

          <div class="nav-flex">

            <% if current_user.admin %>
              <div class="nav-item">
                <%= link_to "My Company", hr_home_path, class: "nav-link" %>
              </div>
            <% end %>
            <div class="nav-item">
              <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
            </div>

            <li class="nav-item dropdown">
              <%= image_tag "moritz.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" id="navbar-dropdown" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>

          </div>

        <% else %>
          <div class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fas fa-cog"></i> Login
            <% end %>
          </div>

        <% end %>

      </div>
    </div>

  </div>
</div>

app/views/shared/_search_form.html.erb
<!-- <div class="col-12 container"> -->
  <div class="search-form <%= locals[:cl] %>">
    <%= form_tag packages_path, method: :get do %>

      <div class="form-inputs">

        <div class="form-group-all">
          <div class="form-group search-form-class">
            <div class="labeled-input">
              <label class="search-label" for="dep_city">From</label>
                <%= text_field_tag :dep_city, nil, as: :string, required: false, class: "form-control search-input", value: params[:dep_city] %>
            </div>
            <div class="labeled-input">
              <label class="search-label" for="dep_city">To</label>
                <%= text_field_tag :arr_city, nil, as: :string, required: false, class: "form-control search-input", value: params[:arr_city] %>
            </div>
          </div>

          <div class="form-group form-group-dates">
            <div class="labeled-input">
              <label class="search-label" for="dep_city">Start date</label>
                <%= text_field_tag :start_date, nil, as: :string, required: false, class: "datepicker form-control", value: params[:start_date] %>
            </div>
            <div class="labeled-input">
              <label class="search-label" for="dep_city">End date</label>
                <%= text_field_tag :end_date, nil, as: :string, required: false, class: "datepicker form-control", value: params[:end_date] %>
            </div>
          </div>
          </div>
          <%= submit_tag "Search", class: "btn-custom btn-custom-green" %>
        </div>
    <% end %>
  </div>
<!-- </div> -->

app/views/shared/_train_card.html.erb
<div class="billboard-card">
  <div class="card card-2">
    <div class="card-content">
      <div class="schedules">
        <ul>
          <li class="tab active">Inward</li>
          <li class="tab">Outward</li>
        </ul>
        <div class="schedule">
          <span>
            <abbr><%= @package.train_from.dep_city %> – <%=@package.train_from.arr_city%></abbr>
            <small>
              <i><%= @package.train_from.category %></i>
              <p><%= @package.start_date.strftime('%b %d, %Y') %>, <%= @package.train_from.dep_time %> – <%= @package.train_from.arr_time %></p>
            </small>
          </span>
        </div>
        <div class="schedule hidden">
          <span>
            <abbr><%= @package.train_to.dep_city %> – <%=@package.train_to.arr_city%></abbr>
            <small>
              <i><%= @package.train_from.category %></i>
              <p><%= @package.end_date.strftime('%b %d, %Y') %>, <%= @package.train_to.dep_time %> – <%= @package.train_to.arr_time %></p>
            </small>
          </span>
        </div>
      </div>
    </div>
    <div class="card-provider">
      <%= image_tag @package.train_from.photo %>
      <small>
        Deutsche Bahn
        <br>
        <%= @package.train_from.train_number %>
      </small>
    </div>
    <div class="card-price">
      <p><%= @package.train_price %> € / Trip</p>
    </div>
  </div>
</div>