config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '', to: 'pages#home', as: :home
  get 'hr_home', to: 'pages#hr_home', as: :hr_home
  root to: 'passthrough#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :packages, only: [:index, :show] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy]

  scope :hr_home do
    resources :company_policies, only: [:edit, :update]
    get 'all_bookings', to: 'pages#all_bookings', as: :all_bookings
  end
end

app/views/pages/all_bookings.html.erb
<!-- index.html.erb -->
<%if current_user.admin %>
  <div class="container page-top-space">
    <%= render 'shared/hr_header' %>
    <%= render 'shared/hr_navigation' %>

    <div class="row">
      <div class="col-12">
        <% if @bookings.empty? %>
          <h1>Your company doesn't have any bookings yet</h1>
          <div class="btn-center">
            <%= link_to 'Book your first trip now', packages_path, class: "btn btn-custom" %>
          </div>
        <% else %>
          <h2>Bookings for <%= current_user.company.name %></h2>
          <ul style="list-style-type: none;">
          <div class="container">
            <div class="row">
              <div class="col-12">
                <%@bookings.each do |booking| %>
                  <li class="booking-item">
                    <div>
                      <p><strong>Employee: <%= booking.user.first_name %> <%= booking.user.last_name %></strong></p>
                      <p><strong>Booking from: <%= booking.created_at.strftime('%a, %d %b %Y %l:%M %p') %> </strong></p>
                      <p><strong>Booking status: <%= booking.status %> </strong></p>
                      <p><strong>Dates: </strong><%= booking.package.start_date.strftime('%b %d, %Y') %> - <%= booking.package.end_date.strftime('%b %d, %Y') %></p>
                      <p><strong>Total price: </strong><%= booking.package.price %> €</p>
                      <br>
                    </div>
                    <div class="btn-bottom">
                      <%= link_to 'Cancel this booking', booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to cancel the booking for #{booking.package.start_date.strftime('%b %d, %Y')} - #{booking.package.end_date.strftime('%b %d, %Y')}?" }, class: "btn btn-custom" %>
                    </div>
                  </li>
                <% end %>
              </div>
            </div>
          </div>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="container page-top-space">
    <div class="row">
      <div class="column">
        <h1 class="text-center">You're not authorized to perform this action</h1>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
  <div class="banner" id= "home-banner">
  <div class="container">
    <div id="home-banner-items">
      <div style ="padding-right: 25px;">
        <h1 id="subheader-home" class="uppcase-font">Reinventing business traveling</h1>
        <br>
        <p class="text-left", id="subheader-home">Book your entire business trip with just 3 clicks. Find your tailored travel package with <strong style="color:#54CEBE">TravelBuddy</strong>.</p>
        <p class="text-left", id="subheader-home">TravelBuddy's algorithm ensures that trips are curated based on your <br>personal preferences and company policy.</p>
      </div>

      <div>
        <%= render 'shared/search_form', locals: { cl: @class }  %>
      </div>

    </div>

  </div>
</div>

app/views/pages/hr_home.html.erb
<%if current_user.admin %>
  <div class="container page-top-space">
    <%= render 'shared/hr_header' %>
    <%= render 'shared/hr_navigation' %>

    <div class="row cost-category">
      <h2>Costs per category</h2>
      <div class="cards-row">
        <div class="card card-2 hr-card">
          <div class="card-content">
            <div class="misc">
              <span>
                <abbr>Hotel <small>Average - <%= current_user.company.spend_on_hotels / User.count %>  € / employee</small></abbr>

                <div class="card-hr-details">
                  <div class="card-hr-content">
                    <p><%= number_with_delimiter(current_user.company.spend_on_hotels, :delimiter => ' ') %> €</i></p>
                    <small>Total cost this month</small>
                  </div>

                  <div class="card-provider">
                    <%= image_tag Hotel.fifth.logo %>
                    <%= image_tag Hotel.second.logo %>
                    <%= image_tag Hotel.third.logo %>
                  </div>
                </div>
              </span>
            </div>
          </div>
        </div>
        <div class="card card-2 hr-card">
          <div class="card-content">
            <div class="misc">
              <span>
                <abbr>Train <small>Average - <%= current_user.company.spend_on_trains / User.count %>  € / employee</small></abbr>

                <div class="card-hr-details">
                  <div class="card-hr-content">
                    <p><%= number_with_delimiter(current_user.company.spend_on_trains, :delimiter => ' ') %> €</i></p>
                    <small>Total cost this month</small>
                  </div>
                   <div class="card-provider">
                    <%= image_tag Train.first.photo %>
                  </div>
                </div>
              </span>
            </div>
          </div>
        </div>
        <div class="card card-2 hr-card">
          <div class="card-content">
            <div class="misc">
              <span>
                <abbr>Car rental <small>Average - <%= current_user.company.spend_on_cars / User.count %>  € / employee</small></abbr>

                <div class="card-hr-details">
                  <div class="card-hr-content">
                    <p><%= number_with_delimiter(current_user.company.spend_on_cars, :delimiter => ' ') %> €</i></p>
                    <small>Total cost this month</small>
                  </div>
                  <div class="card-provider">
                    <%= image_tag Car.first.photo %>
                    <%= image_tag Car.last.photo %>
                  </div>
                </div>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row employees-cost">
      <h2>Employees travel costs</h2>
      <div class="progress-items">
        <% max_costs = current_user.company.top_users.first[1] %>
        <% current_user.company.top_users.each do |user, total| %>
          <div class="progress-item">
            <p><%= user.first_name %> <%= user.last_name %> <small><%= number_with_delimiter(total, :delimiter => ' ') %> €</small></p>
            <div class="progress">
              <% num = (100 * total) / max_costs %>
              <div class="progress-bar" role="progressbar" style="width: <%=num %>%"></div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
<% else %>
  <div class="container page-top-space">
    <div class="row">
      <div class="column">
        <h1 class="text-center">You're not authorized to perform this action</h1>
      </div>
    </div>
  </div>
<% end %>